apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.x"  # Use the latest 4.x version
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: networking
  values:
    controller:
      service:
        type: LoadBalancer