apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.containerPort }}
          envFrom:
            - secretRef:
                name: {{ .Values.app.secretName }}
          env:
            {{- range $k, $v := .Values.app.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.app.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.app.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.app.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.app.healthCheck.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.app.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.app.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.app.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.app.healthCheck.failureThreshold }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
