---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  chart:
    spec:
      chart: pihole
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mojo2600
      version: 2.5.8
  interval: 1m0s
  values:
    persistentVolumeClaim:
      enabled: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
    serviceWeb:
      loadBalancerIP: 10.64.1.1
      type: LoadBalancer
      http:
        port: 8080
      https:
        port: 8443
    serviceDns:
      loadBalancerIP: 10.64.1.2
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: network-services
        metallb.universe.tf/allow-shared-ip: pihole-svc
    adminPassword: admin