---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  chart:
    spec:
      chart: pihole
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mojo2600
      version: 2.5.8
  interval: 1m1s
  values:
    persistentVolumeClaim:
      enabled: true
    ingress:
      enabled: true
    serviceWeb:
      loadBalancerIP: 192.168.2.100
      type: LoadBalancer
      externalTrafficPolicy: Cluster
      http:
        port: 8080
      https:
        port: 8443
      annotations:
        metallb.universe.tf/address-pool: network-services
    serviceDns:
      loadBalancerIP: 192.168.2.101
      type: LoadBalancer
      externalTrafficPolicy: Cluster
      annotations:
        metallb.universe.tf/address-pool: network-services
    adminPassword: admin