apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: content-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1000Gi