apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: content3-pvc
  namespace: media
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1000Gi