apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-pvc
  namespace: factorio
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi