apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-movie-pv
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /mnt/nas/Data/Movies
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - home-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-movie-pvc
  namespace: media
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1000Gi