---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wireguard
  namespace: media
spec:
  chart:
    spec:
      chart: wireguard
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: 1.3.2
  interval: 1m0s
  values:
    ingress:
      main:
        enabled: true
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local