---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: assetto-server-manager
  namespace: assetto
spec:
  chart:
    spec:
      chart: ./charts/assetto-server-manager
      sourceRef:
        kind: GitRepository
        name: github-repo
        namespace: flux-system
  interval: 1m0s
  values:

    persistence:
      config:
        enabled: true
        mountPath: /home/assetto/server-manager/assetto/config.yml
        subPath: config.yml
        type: custom
        volumeSpec:
          configMap:
            name: assetto-server-manager-config