---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: github-repo
  namespace: assetto
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh://git@github.com/tseruga/home-k8s