image:
  repository: seejy/assetto-server-manager
  tag: v1.7.9
  pullPolicy: IfNotPresent


service:
  main:
    ports:
      http: 
        port: 8772
    type: LoadBalancer
    loadBalancerIP: 192.168.1.212
    externalTrafficPolicy: Local


persistence:
  config:
    enabled: true
    mountPath: /home/assetto/server-manager/assetto/config.yml
    subPath: config.yml
    type: custom
    volumeSpec:
      configMap:
        name: assetto-server-manager-config