---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: ingress
spec:
  chart:
    spec:
      chart: nginx-stable/nginx-ingress
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
      version: 0.4.1
  interval: 1m0s