---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: anythingllm
  namespace: ai
spec:
  chart:
    spec:
      chart: anything-llm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: anything-llm
      version: 8.14.0
  interval: 1m0s
  values:
    image:
      tag: 1.9.0
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.217
      externalTrafficPolicy: Local
    