apiVersion: v2
name: plex-watchlist-updater
description: A Helm chart for Plex Watchlist to Radarr Profile Updater
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.3.0 