#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: plex-watchlist-updater
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [application documentation](https://github.com/your-org/plex-watchlist-updater).
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Plex server URL (will be overridden by secret)
  PLEX_URL: "http://plex.media.svc.cluster.local:32400"
  # -- Radarr server URL (will be overridden by secret) 
  RADARR_URL: "http://radarr.media.svc.cluster.local:7878"
  # -- Target quality profile name
  TARGET_PROFILE: "HD-1080p"

# -- Configure environment variables from secrets
envFrom:
  - secretRef:
      name: plex-watchlist-updater-secrets

# -- Configures service settings for the chart.
service:
  main:
    ports:
      http:
        port: 8080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
persistence: {}

# -- Configures the probes for the main Pod.
probes:
  # -- Liveness probe configuration
  liveness:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

  # -- Readiness probe configuration  
  readiness:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

  # -- Startup probe configuration
  startup:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 30

# -- Configure application-specific settings
config:
  # -- Run interval in minutes (how often to check the watchlist)
  interval: 60
  # -- Target quality profile to upgrade movies to
  targetProfile: "HD-1080p"

# Configure args for the main command
args:
  - "--continuous"
  - "--interval"
  - "$(INTERVAL)"

# -- Configure additional environment variables
additionalEnv:
  INTERVAL: "{{ .Values.config.interval }}" 