---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-config
  {{- with (merge (.Values.labels | default dict) (include "common.labels" $ | fromYaml)) }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (merge (.Values.annotations | default dict) (include "common.annotations" $ | fromYaml)) }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    # Plex Watchlist to Radarr Profile Updater Configuration
    # Note: API credentials will come from environment variables

    # Plex server configuration
    plex:
      url: "{{ .Values.env.PLEX_URL }}"
      token: ""  # Will be set via environment variable

    # Radarr server configuration  
    radarr:
      url: "{{ .Values.env.RADARR_URL }}"
      api_key: ""  # Will be set via environment variable

    # Target quality profile name to upgrade movies to
    target_profile: "{{ .Values.config.targetProfile }}"

    # Logging configuration
    logging:
      level: "INFO"
      file: "plex_radarr_updater.log" 