image:
  repository: meisnate12/plex-meta-manager
  tag: latest
  pullPolicy: IfNotPresent

persistence:
  config:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 1Gi

ports:
  http: 
    port: 8080
type: LoadBalancer
loadBalancerIP: 192.168.1.213
externalTrafficPolicy: Local