---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  chart:
    spec:
      chart: bazarr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: 10.6.2
  interval: 1m0s
  values:
    image:
      repository: lscr.io/linuxserver/bazarr
      tag: v1.5.2-ls304
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.216
        externalTrafficPolicy: Local
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi