---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: deluge
  namespace: media
spec:
  chart:
    spec:
      chart: deluge
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: 5.2.0
  interval: 1m0s
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.208
        externalTrafficPolicy: Local
    settings:
      automaticPortSetup: True
    persistence:
      content:
        enabled: true
        type: pvc
        existingClaim: content-pvc
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi