apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eratztv
  namespace: media
spec:
  interval: 1m0s
  chart:
    spec:
      chart: eratztv
      version: 9.10.0
      sourceRef:
        kind: HelmRepository
        name: truecharts-oci
        namespace: flux-system
      reconcileStrategy: ChartVersion
  values:
    ingress:
      main:
        enabled: true
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.223
        externalTrafficPolicy: Local
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi