apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ersatztv
  namespace: media
spec:
  releaseName: ersatztv
  interval: 5m
  chart:
    spec:
      chart: ./charts/ersatztv
      sourceRef:
        kind: GitRepository
        name: github-repo
        namespace: flux-system
      interval: 1m
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.223
        externalTrafficPolicy: Local
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi