---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grocy
  namespace: media
spec:
  chart:
    spec:
      chart: grocy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: 8.5.2
  interval: 1m0s
  values:
    image:
      tag: version-v4.2.0
    ingress:
      main:
        enabled: true
    service:
      main:
        ports:
          http:
            port: 8111
        type: LoadBalancer
        loadBalancerIP: 192.168.1.221
        externalTrafficPolicy: Local
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi