---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: k8s-at-home
  namespace: media
spec:
  interval: 1m0s
  url: https://k8s-at-home.com/charts/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: truecharts-oci
  namespace: flux-system
  type: oci
spec:
  interval: 5m
  url: oci://oci.trueforge.org/truecharts/