---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  chart:
    spec:
      chart: jackett
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: 11.4.0
  interval: 1m0s
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.209
        externalTrafficPolicy: Local