---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  chart:
    spec:
      chart: jellyfin
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: 6.2.2
  interval: 1m0s
  values:
    image:
      repository: jellyfin/jellyfin
      tag: 10.10.3
      pullPolicy: IfNotPresent
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.222
        externalTrafficPolicy: Local
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi