---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mealie
  namespace: media
spec:
  chart:
    spec:
      chart: mealie
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: 5.1.2                                                                                                                    
  postRenderers:                                                                                                           
    - kustomize:                                                                                                           
        patches:                                                                                                           
          - target:                                                                                                        
              kind: Deployment                                                                                             
              name: mealie                                                                                                 
            patch: |                                                                                                       
              apiVersion: apps/v1                                                                                          
              kind: Deployment                                                                                             
              metadata:                                                                                                    
                name: mealie                                                                                               
              spec:                                                                                                        
                template:                                                                                                  
                  spec:
                    containers:
                      - name: mealie-api
                        $patch: delete
                      - name: mealie
                        livenessProbe:
                          tcpSocket:
                            port: 9000
                        readinessProbe:
                          tcpSocket:
                            port: 9000
                        startupProbe:
                          tcpSocket:
                            port: 9000
                    volumes:
                      - name: api-data
                        $patch: delete
          - target:
              kind: Service
              name: mealie
            patch: |
              apiVersion: v1
              kind: Service
              metadata:
                name: mealie
              spec:
                ports:
                  - name: http
                    $patch: delete
          - target:
              kind: Ingress
              name: mealie
            patch: |
              apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: mealie
              spec:
                rules:
                  - host: mealie.tseruga.com
                    http:
                      paths:
                        - path: /
                          pathType: Prefix
                          backend:
                            service:
                              name: mealie
                              port:
                                number: 9000
  interval: 1m0s
  values:
    image:
      repository: ghcr.io/mealie-recipes/mealie
      tag: "v3.20.1"
    api:
      image:
        repository: ghcr.io/mealie-recipes/mealie
        tag: "v3.20.1"
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        ingressClassName: nginx
        hosts:
          - host: mealie.tseruga.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: mealie-tls
            hosts:
              - mealie.tseruga.com
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.220
        externalTrafficPolicy: Local
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi