---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  chart:
    spec:
      chart: overseerr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: 5.3.1
  interval: 1m0s
  values:
    image:
      tag: 1.33.0
    ingress:
      main:
        enabled: true
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi