---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      chart: plex
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: 2.1.1
  interval: 1m0s
  values:
    service:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.209
        externalTrafficPolicy: Local