---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex-meta-manager
  namespace: media
spec:
  chart:
    spec:
      chart: ./charts/plex-meta-manager
      sourceRef:
        kind: GitRepository
        name: github-repo
        namespace: flux-system
  interval: 1m0s
  values:
    service:
      main:
        ports:
          http:
            port: 8080
    probes:
      liveness:
        enabled: false
  persistence:
    config:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      size: 1Gi