---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex-meta
  namespace: media
spec:
  chart: ./charts/plex-meta-manager
  sourceRef:
    name: plex-meta-manager
    kind: GitRepository
  interval: 1m0s
  values:
    service:
      main:
        ports:
          http:
            port: 8080
    probes:
      liveness:
        enabled: false
    persistence:
      config:
        enabled: true
        type: "custom"
        volumeSpec:
          secret:
            secretName: pmm-config
        subPath:
          - path: config.yml
            mountPath: "/config/config.yml"
      