apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex-movie-randomizer
  namespace: media
spec:
  releaseName: plex-movie-randomizer
  interval: 5m
  chart:
    spec:
      chart: ./charts/plex-movie-randomizer
      sourceRef:
        kind: GitRepository
        name: github-repo
        namespace: flux-system
      interval: 1m
  values:
    namespace: media
    app:
      name: plex-movie-randomizer
      image:
        repository: tseruga/plex-movie-randomizer
        tag: latest
        pullPolicy: Always
      
      replicas: 1
      
      service:
        type: ClusterIP
        port: 80
        targetPort: 80
      
      ingress:
        enabled: true
        host: random.tseruga.com  # Update this to your domain
        tls: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
      
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
      
      healthCheck:
        enabled: true
        path: /health
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3 