---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent-vpn
  namespace: media
spec:
  chart:
    spec:
      chart: qbittorrent
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: 13.4.2
  interval: 1m0s
  values:
    podSecurityContext:
      allowPrivilegeEscalation: false
      runAsUser: 0
    ingress:
      main:
        enabled: true
        ports:
          http:
            port: 8080
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.220
        externalTrafficPolicy: Local
    persistence:
      content:
        enabled: true
        type: pvc
        existingClaim: content-pvc
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi
      shared:
        enabled: true
        type: emptyDir
        mountPath: /shared
    addons:
      vpn:
        enabled: true
        # This Should be set to `openvpn`. This will set the add-on to use the default settings for OpenVPN based connections.
        type: openvpn

        openvpn:
          # This gets read by the Helm chart. The default OpenVPN image reads this and uses it to connect to the VPN provider.
          authSecret: openvpn-auth

        # If the podSecurityContext is set to run as a different user, make sure to run the OpenVPN container as root. 
        # This is required for it to be able to read certain configuration files. 
        securityContext:
          runAsGroup: 0
          runAsUser: 0

        env:
          # Set this environment variable to 'on' to make sure all traffic gets routed through the VPN container.
          # Make sure to check the other environment variables for the OpenVPN image to see how you can exclude certain
          # traffic from these firewall rules.
          FIREWALL: 'on'

        # The .ovpn file provided by your VPN provider goes here.
        #
        # Any CA / certificate must either be placed inline, or provided through an additionalVolumeMount so that OpenVPN can find it.
        #
        # Pay close attention to the last 3 lines in this file. They must be added if you wish to run a script when the connection
        # is opened / closed.
        configFileSecret: openvpn-config

        # The scripts that get run when the VPN connection opens/closes are defined here.
        # The default scripts will write a string to represent the current connection state to a file.
        # Our qBittorrent image has a feature that can wait for this file to contain the word 'connected' before actually starting the application.
        scripts:
          up: |-
            #!/bin/bash
            /etc/openvpn/up.sh
            echo "connected" > /shared/vpnstatus

          down: |-
            #!/bin/bash
            /etc/openvpn/down.sh
            echo "disconnected" > /shared/vpnstatus