---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  chart:
    spec:
      chart: qbittorrent
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: 13.3.0
  interval: 1m0s
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.208
        externalTrafficPolicy: Local
    settings:
      automaticPortSetup: True
    persistence:
      content:
        enabled: true
        type: pvc
        existingClaim: content-pvc