---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  chart:
    spec:
      chart: radarr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: 16.1.0
  interval: 1m0s
  values:
    image:
      repository: ghcr.io/onedr0p/radarr-develop
      tag: 5.20.1
    ingress:
      main:
        enabled: true
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.211
        externalTrafficPolicy: Local
    persistence:
      content:
        enabled: true
        type: pvc
        existingClaim: content-pvc
      content2:
        enabled: true
        type: pvc
        existingClaim: content2-pvc
      content3:
        enabled: true
        type: pvc
        existingClaim: content3-pvc
      nas:
        enabled: true
        type: pvc
        existingClaim: nas-movie-pvc
      downloads:
        enabled: true
        type: pvc
        existingClaim: nas-downloads-pvc
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi