---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  chart:
    spec:
      chart: sonarr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: 16.1.0
  interval: 1m0s
  values:
    image:
      repository: ghcr.io/onedr0p/sonarr
      tag: "4.0.12.2823"
    ingress:
      main:
        enabled: true
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.207
        externalTrafficPolicy: Local
    persistence:
      content:
        enabled: true
        type: pvc
        existingClaim: content-pvc
      content2:
        enabled: true
        type: pvc
        existingClaim: content2-pvc
      content3:
        enabled: true
        type: pvc
        existingClaim: content3-pvc
      nas:
        enabled: true
        type: pvc
        existingClaim: nas-tv-pvc
      downloads:
        enabled: true
        type: pvc
        existingClaim: nas-downloads-pvc
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi
    securityContext:
      runAsUser: 568
      runAsGroup: 568