---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  chart:
    spec:
      chart: sonarr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: 16.1.0
  interval: 1m0s
  values:
    ingress:
      main:
        enabled: true
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.200
        annotations:
          metallb.universe.tf/address-pool: network-services
          metallb.universe.tf/allow-shared-ip: pihole-svc