---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn
  labels:
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: pod-gateway
      version: 5.4.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      interval: 1m

  # See https://github.com/k8s-at-home/charts/blob/master/charts/pod-gateway/values.yaml
  values:
    routed_namespaces:
      - downloads
    settings:
      VPN_INTERFACE: wg0
      VXLAN_ID: 43
      NOT_ROUTED_TO_GATEWAY_CIDRS: "172.16.0.0/12 10.0.0.0/8 192.168.0.0/16"
      VPN_LOCAL_CIDRS: "172.16.0.0/12 10.0.0.0/8 192.168.0.0/16"
    addons:
      vpn:
        enabled: true
        # You might use `openvpn` or `wireguard`
        type: openvpn
        openvpn:
        # VPN settings stored in secret `vpnConfig`. The secret mus have a key
        # a key called `vpnConfigfile` with the openvpn/wireguard config files in them
        configFileSecret: openvpn-config

        # livenessProbe:
        #   exec:
        #     # In the example bellow the VPN output is in Belgic (BE) - change appropiatly
        #     command:
        #       - sh
        #       - -c
        #       - if [ $(wget -q -O- https://ipinfo.io/country) == 'US' ]; then exit 0; else exit $?; fi
        #   initialDelaySeconds: 30
        #   periodSeconds: 60
        #   failureThreshold: 1

        networkPolicy:
          enabled: true

          egress:
            - to:
              - ipBlock:
                  cidr: 0.0.0.0/0
              ports:
              # VPN traffic port - change if your provider uses a different port
              - port: 443
                protocol: UDP
            - to:
                # Allow traffic within K8S - change if your K8S cluster uses a different CIDR
              - ipBlock:
                  cidr: 10.0.0.0/8