apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ranked-choice-vote
  namespace: vote
spec:
  releaseName: ranked-choice-vote
  interval: 5m
  chart:
    spec:
      chart: ./charts/ranked-choice-vote
      sourceRef:
        kind: GitRepository
        name: github-repo
        namespace: flux-system
      interval: 1m
  values:
    namespace: vote
    frontend:
      name: ranked-choice-vote
      image:
        repository: tseruga/ranked-choice-vote
        tag: 1.1.7
      service:
        type: ClusterIP
        port: 80
      ingress:
        host: vote.tseruga.com

    backend:
      name: ranked-choice-vote-api
      image:
        repository: tseruga/ranked-choice-vote-api
        tag: 1.0.10
      service:
        type: ClusterIP
        port: 5000