apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ranked-choice-vote
  namespace: vote
spec:
  releaseName: ranked-choice-vote
  interval: 5m
  chart:
    spec:
      chart: ./charts/ranked-choice-vote
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    namespace: vote
    frontend:
      image:
        tag: latest
      ingress:
        host: vote.tseruga.com
    backend:
      image:
        tag: latest